-- =====================================================================
--  HIỆP SĨ SỐ HỌC: CẬP NHẬT V2, NGÂN HÀNG ĐỀ TRÊN MÁY CHỦ
--  Chạy SAU schema.sql. Chạy lại nhiều lần vẫn an toàn.
-- =====================================================================

-- ---------- 1. Danh sách giá trị (hiện thành menu thả xuống) ----------
do $$ begin create type public.muc_do    as enum ('de', 'trung_binh', 'kho');                      exception when duplicate_object then null; end $$;
do $$ begin create type public.loai_cau  as enum ('trac_nghiem', 'dien');                          exception when duplicate_object then null; end $$;
do $$ begin create type public.kieu_dien as enum ('so', 'tap_hop', 'luy_thua', 'dau', 'phan_so');  exception when duplicate_object then null; end $$;
do $$ begin create type public.dap_an    as enum ('A', 'B', 'C', 'D');                             exception when duplicate_object then null; end $$;

-- ---------- 2. Bảng hầm ngục (chủ đề) ----------
create table if not exists public.stages (
  id         text primary key,
  name       text not null,
  sort_order int  not null default 0
);
comment on table public.stages is 'Các hầm ngục (chủ đề). sort_order quyết định thứ tự mở khóa.';

-- ---------- 3. Bảng câu hỏi ----------
create table if not exists public.questions (
  id          text primary key,
  stage_id    text not null references public.stages(id) on update cascade,
  muc_do      public.muc_do   not null default 'trung_binh',
  loai        public.loai_cau not null default 'trac_nghiem',
  cau_hoi     text not null,
  lua_chon_a  text not null,
  lua_chon_b  text not null,
  lua_chon_c  text not null,
  lua_chon_d  text not null,
  dap_an_dung public.dap_an not null,
  kieu_dien   public.kieu_dien,
  dap_an_dien text,
  tien_to     text not null default '',
  don_vi      text not null default '',
  goi_y       text not null default '',
  loi_giai    text not null default '',
  hien_thi    boolean not null default true,
  cap_nhat    timestamptz not null default now(),
  constraint cau_dien_can_dap_an check (loai = 'trac_nghiem' or (kieu_dien is not null and coalesce(btrim(dap_an_dien), '') <> ''))
);
comment on table  public.questions is 'Ngân hàng đề. Câu dễ: quái thường. Câu trung bình: quái tinh anh. Câu khó: quái chính.';
comment on column public.questions.id          is 'Mã câu, không trùng nhau, ví dụ de10_tl3';
comment on column public.questions.muc_do      is 'de = Dễ, trung_binh = Trung bình, kho = Khó';
comment on column public.questions.loai        is 'trac_nghiem = chọn A/B/C/D, dien = học sinh tự điền đáp án';
comment on column public.questions.cau_hoi     is 'Nội dung câu hỏi. Công thức toán viết giữa hai dấu $, ví dụ $x^2$';
comment on column public.questions.dap_an_dung is 'Lựa chọn đúng (A, B, C hoặc D). Câu điền vẫn nên điền đủ 4 lựa chọn';
comment on column public.questions.kieu_dien   is 'Chỉ cho câu điền: so, tap_hop (0;1;4), luy_thua (10^12), dau (> < =), phan_so (13/56)';
comment on column public.questions.dap_an_dien is 'Chỉ cho câu điền: đáp án chuẩn, ví dụ 420 hoặc 52,5 hoặc 0;1;4';
comment on column public.questions.tien_to     is 'Chữ hiện trước ô điền, ví dụ $x =$';
comment on column public.questions.don_vi      is 'Chữ hiện sau ô điền, ví dụ cm hoặc quả';
comment on column public.questions.hien_thi    is 'Bỏ tích để ẩn câu khỏi game mà không cần xóa';
create index if not exists questions_stage_idx on public.questions (stage_id) where hien_thi;

-- tự cập nhật thời gian sửa
create or replace function public.touch_question() returns trigger language plpgsql as $$
begin new.cap_nhat := now(); return new; end $$;
drop trigger if exists questions_touch on public.questions;
create trigger questions_touch before update on public.questions for each row execute function public.touch_question();

alter table public.stages    enable row level security;
alter table public.questions enable row level security;

-- ---------- 4. Game tải đề qua hàm này (ai cũng gọi được) ----------
create or replace function public.get_questions()
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'id', q.id, 'stageId', q.stage_id, 'stageName', s.name, 'stageOrder', s.sort_order,
      'type', case when q.loai = 'dien' then 'input' else 'choice' end,
      'difficulty', case q.muc_do when 'de' then 1 when 'trung_binh' then 2 else 3 end,
      'question', q.cau_hoi,
      'options', jsonb_build_array('A. ' || q.lua_chon_a, 'B. ' || q.lua_chon_b, 'C. ' || q.lua_chon_c, 'D. ' || q.lua_chon_d),
      'correctIndex', case q.dap_an_dung when 'A' then 0 when 'B' then 1 when 'C' then 2 else 3 end,
      'answerKind', case q.kieu_dien when 'so' then 'number' when 'tap_hop' then 'set' when 'luy_thua' then 'power'
                                     when 'dau' then 'sign' when 'phan_so' then 'fraction' end,
      'answer', q.dap_an_dien, 'prefix', q.tien_to, 'unit', q.don_vi,
      'hint', q.goi_y, 'explanation', q.loi_giai
    ) order by s.sort_order, q.muc_do, q.id), '[]'::jsonb)
  from questions q join stages s on s.id = q.stage_id
  where q.hien_thi;
$$;
revoke execute on function public.get_questions() from public;
grant  execute on function public.get_questions() to anon, authenticated;

-- ---------- 5. Điểm tối đa tự tính theo số câu của hầm ----------
create or replace function public.submit_run(p_stage text, p_score int, p_stars int, p_correct int, p_wrong int)
returns json language plpgsql security definer set search_path = public as $$
declare v_max int; v_n int; v_recent int; v_best int; v_rank bigint;
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  if not exists (select 1 from players where id = auth.uid()) then raise exception 'no profile'; end if;
  select count(*) into v_n from questions where stage_id = p_stage and hien_thi;
  if v_n > 0 then v_max := 150 * v_n + 500;
  else select max_score into v_max from stage_limits where stage_id = p_stage; end if;
  if v_max is null then raise exception 'unknown stage'; end if;
  if p_score < 0 or p_score > v_max then raise exception 'score out of range'; end if;
  if p_stars not between 1 and 3 or p_correct < 0 or p_wrong < 0 or p_correct + p_wrong > 500 then
    raise exception 'invalid run';
  end if;
  select count(*) into v_recent from runs where player_id = auth.uid() and created_at > now() - interval '1 hour';
  if v_recent >= 20 then raise exception 'too many submissions'; end if;
  insert into runs (player_id, stage_id, score, stars, correct, wrong)
  values (auth.uid(), p_stage, p_score, p_stars, p_correct, p_wrong);
  select max(score) into v_best from runs where player_id = auth.uid() and stage_id = p_stage;
  select count(*) + 1 into v_rank from (
    select player_id, max(score) s from runs where stage_id = p_stage group by player_id
  ) t where t.s > v_best;
  return json_build_object('best', v_best, 'rank', v_rank);
end $$;
revoke execute on function public.submit_run(text, int, int, int, int) from public, anon;
grant  execute on function public.submit_run(text, int, int, int, int) to authenticated;

-- ---------- 6. Bảng thống kê dễ đọc (xem trong Table Editor) ----------
create or replace view public.thong_ke_cau_hoi with (security_invoker = true) as
  select q.id, s.name as ham, q.muc_do, left(q.cau_hoi, 80) as cau_hoi,
         coalesce(st.attempts, 0) as so_luot, coalesce(st.correct, 0) as so_dung,
         round(100.0 * st.correct / nullif(st.attempts, 0), 1) as ti_le_dung
  from questions q join stages s on s.id = q.stage_id
  left join question_stats st on st.question_id = q.id;
revoke all on public.thong_ke_cau_hoi from anon, authenticated;

-- ---------- 7. Dữ liệu ban đầu: 5 hầm và 60 câu hỏi ----------
-- Chỉ thêm câu chưa có; câu bạn đã sửa trong Table Editor sẽ KHÔNG bị ghi đè khi chạy lại.
insert into public.stages (id, name, sort_order) values ($hsh$stage_1$hsh$, $hsh$Thung lũng Phép thuật$hsh$, 1) on conflict (id) do nothing;
insert into public.stages (id, name, sort_order) values ($hsh$stage_2$hsh$, $hsh$Mê cung Ẩn số$hsh$, 2) on conflict (id) do nothing;
insert into public.stages (id, name, sort_order) values ($hsh$stage_3$hsh$, $hsh$Khu rừng Chia hết$hsh$, 3) on conflict (id) do nothing;
insert into public.stages (id, name, sort_order) values ($hsh$stage_4$hsh$, $hsh$Vương quốc Hình học$hsh$, 4) on conflict (id) do nothing;
insert into public.stages (id, name, sort_order) values ($hsh$stage_5$hsh$, $hsh$Tháp Hư Không$hsh$, 5) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl1a$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Thực hiện phép tính: $44 + 73 + 96 - 53$$hsh$, $hsh$150$hsh$, $hsh$160$hsh$, $hsh$170$hsh$, $hsh$180$hsh$, 'B', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Kết hợp hợp lý: $(44 + 96) + (73 - 53)$.$hsh$, $hsh$Ta có: $(44 + 96) + (73 - 53) = 140 + 20 = 160$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tn1$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Tập hợp các chữ cái trong cụm từ “CÓ CHÍ THÌ NÊN” có số phần tử là:$hsh$, $hsh$7$hsh$, $hsh$11$hsh$, $hsh$4$hsh$, $hsh$12$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Liệt kê các chữ cái khác nhau (mỗi chữ cái chỉ tính một lần, không tính dấu thanh).$hsh$, $hsh$Các chữ cái khác nhau xuất hiện là: C, O, H, I, T, N, Ê. Vậy tập hợp có 7 phần tử.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tn3$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Lương Thế Vinh sinh năm 1441 tại Liên Bảo. Ông sinh ra vào thế kỉ nào?$hsh$, $hsh$XIII$hsh$, $hsh$XIX$hsh$, $hsh$XV$hsh$, $hsh$XIV$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Năm 1441 thuộc khoảng từ năm 1401 đến năm 1500.$hsh$, $hsh$Năm 1441 thuộc thế kỉ thứ 15, viết bằng chữ số La Mã là XV.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tn1$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Các số La Mã $XI; XIX; XVII$ được đọc lần lượt là:$hsh$, $hsh$11; 19; 17$hsh$, $hsh$11; 21; 17$hsh$, $hsh$9; 19; 17$hsh$, $hsh$11; 19; 18$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$X = 10, IX = 9, VII = 7.$hsh$, $hsh$$XI = 11$, $XIX = 19$, $XVII = 17$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tl1a$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Tính nhanh: $2^3 \cdot 17 - 2^3 \cdot 14$$hsh$, $hsh$24$hsh$, $hsh$16$hsh$, $hsh$8$hsh$, $hsh$32$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đặt thừa số chung: $2^3 \cdot (17 - 14)$.$hsh$, $hsh$$2^3 \cdot (17 - 14) = 8 \cdot 3 = 24$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tn1$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Cho tập hợp $A = \{n \in \mathbb{N} \mid 3 \le n < 10\}$. Số phần tử của tập hợp $A$ là:$hsh$, $hsh$5$hsh$, $hsh$6$hsh$, $hsh$7$hsh$, $hsh$8$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Các phần tử gồm: 3, 4, 5, 6, 7, 8, 9.$hsh$, $hsh$Số phần tử: $(9 - 3) + 1 = 7$ phần tử.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tn2$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Mỗi phòng học có 45 chỗ ngồi. Cần ít nhất mấy phòng để xếp đủ cho 185 học sinh khối 6?$hsh$, $hsh$3 phòng$hsh$, $hsh$4 phòng$hsh$, $hsh$5 phòng$hsh$, $hsh$6 phòng$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Thực hiện phép chia có dư: $185 : 45 = 4$ dư 5.$hsh$, $hsh$Vì $185 : 45 = 4$ dư 5 nên cần thêm 1 phòng nữa cho 5 em còn lại, tổng cộng cần ít nhất 5 phòng.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tn1$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Tập hợp M các số tự nhiên lớn hơn 2 và nhỏ hơn hoặc bằng 8 được viết là:$hsh$, $hsh$$M = \{3; 4; 5; 7; 8\}$$hsh$, $hsh$$M = \{x \in \mathbb{N} \mid 2 < x \le 8\}$$hsh$, $hsh$$M = \{x \in \mathbb{N} \mid 3 \le x < 10\}$$hsh$, $hsh$$M = \{x \in \mathbb{N} \mid x \le 8\}$$hsh$, 'B', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Lớn hơn 2 tức là $> 2$, nhỏ hơn hoặc bằng 8 là $\le 8$.$hsh$, $hsh$Cách viết chỉ ra tính chất đặc trưng chính xác là $M = \{x \in \mathbb{N} \mid 2 < x \le 8\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tn1$hsh$, $hsh$stage_1$hsh$, 'de', 'trac_nghiem', $hsh$Cho tập hợp $A = \{2; 0; 1; 6\}$. Hỏi tập hợp $A$ có bao nhiêu phần tử?$hsh$, $hsh$4$hsh$, $hsh$3$hsh$, $hsh$5$hsh$, $hsh$6$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đếm số lượng các số phân biệt nằm trong dấu ngoặc nhọn $\{\}$.$hsh$, $hsh$Tập hợp $A$ gồm các phần tử là $2; 0; 1; 6$. Như vậy tập hợp $A$ có tất cả $4$ phần tử.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tn2$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Tích của 12 thừa số 10 ($10 \cdot 10 \dots 10$) được viết dưới dạng một lũy thừa là (nhập theo dạng $a^b$, ví dụ 2^5):$hsh$, $hsh$$10^{14}$$hsh$, $hsh$$100^6$$hsh$, $hsh$$100^{12}$$hsh$, $hsh$$10^{15}$$hsh$, 'B', 'luy_thua', $hsh$10^12$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tích của 12 thừa số 10 là $10^{12}$. Chú ý biến đổi: $10^{12} = (10^2)^6$.$hsh$, $hsh$Tích của 12 thừa số 10 là $10^{12} = (10^2)^6 = 100^6$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl1a$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Thực hiện phép tính: $23 \cdot 65 + 35 \cdot 23 - 2023^0$$hsh$, $hsh$2299$hsh$, $hsh$2300$hsh$, $hsh$2301$hsh$, $hsh$2200$hsh$, 'A', 'so', $hsh$2299$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đặt 23 làm nhân tử chung: $23 \cdot (65 + 35) - 1$.$hsh$, $hsh$Ta có: $23 \cdot (65 + 35) - 1 = 23 \cdot 100 - 1 = 2300 - 1 = 2299$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl1b$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Tính giá trị biểu thức: $1024 : (2^4 \cdot 19 - 2^4 \cdot 11) + 5 \cdot 3^2$$hsh$, $hsh$45$hsh$, $hsh$53$hsh$, $hsh$61$hsh$, $hsh$37$hsh$, 'B', 'so', $hsh$53$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tính cụm ngoặc: $2^4 \cdot (19 - 11) = 16 \cdot 8 = 128 = 2^7$.$hsh$, $hsh$Ta có: $1024 : 128 + 5 \cdot 9 = 8 + 45 = 53$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tl1a$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Thực hiện phép tính: $60 - [120 - (42 - 33)^2]$$hsh$, $hsh$21$hsh$, $hsh$39$hsh$, $hsh$41$hsh$, $hsh$19$hsh$, 'A', 'so', $hsh$21$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Trong ngoặc tròn: $42 - 33 = 9$. Ngoặc vuông: $120 - 9^2 = 120 - 81 = 39$.$hsh$, $hsh$Kết quả: $60 - 39 = 21$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tl1c$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Thực hiện phép tính: $6^7 : 6^5 - 3 \cdot 2^3 + 23^0$$hsh$, $hsh$13$hsh$, $hsh$11$hsh$, $hsh$12$hsh$, $hsh$15$hsh$, 'A', 'so', $hsh$13$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$$6^7 : 6^5 = 6^2 = 36$, $3 \cdot 8 = 24$, $23^0 = 1$.$hsh$, $hsh$Ta có: $36 - 24 + 1 = 13$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tl1b$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Tính nhanh: $57 \cdot 115 - 57 \cdot 15 + 57$$hsh$, $hsh$5700$hsh$, $hsh$5757$hsh$, $hsh$570$hsh$, $hsh$5800$hsh$, 'B', 'so', $hsh$5757$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đặt thừa số chung: $57 \cdot (115 - 15 + 1)$.$hsh$, $hsh$$57 \cdot (115 - 15 + 1) = 57 \cdot 101 = 5757$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl1a$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Thực hiện phép tính: $160 : \{17 + [3^2 \cdot 5 - (14 + 2^{11} : 2^8)]\}$$hsh$, $hsh$2$hsh$, $hsh$4$hsh$, $hsh$8$hsh$, $hsh$10$hsh$, 'B', 'so', $hsh$4$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Thực hiện phép chia lũy thừa trước: $2^{11} : 2^8 = 2^{11-8} = 2^3 = 8$.$hsh$, $hsh$Thứ tự tính: 
- Trong ngoặc tròn: $14 + 2^3 = 14 + 8 = 22$.
- Trong ngoặc vuông: $3^2 \cdot 5 - 22 = 9 \cdot 5 - 22 = 45 - 22 = 23$.
- Trong ngoặc nhọn: $17 + 23 = 40$.
- Kết quả: $160 : 40 = 4$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl1b$hsh$, $hsh$stage_1$hsh$, 'trung_binh', 'dien', $hsh$Tính giá trị biểu thức: $345 - 150 : \left[(3^3 - 24)^2 + 21\right] + 2016^0$$hsh$, $hsh$340$hsh$, $hsh$341$hsh$, $hsh$346$hsh$, $hsh$350$hsh$, 'B', 'so', $hsh$341$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Lưu ý $3^3 = 27$ và $2016^0 = 1$.$hsh$, $hsh$- $3^3 - 24 = 27 - 24 = 3$.
- $(3)^2 + 21 = 9 + 21 = 30$.
- $150 : 30 = 5$.
- $2016^0 = 1$.
- Kết quả: $345 - 5 + 1 = 341$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl1b$hsh$, $hsh$stage_1$hsh$, 'kho', 'dien', $hsh$Tính hợp lý: $53 \cdot 64 + 53 \cdot 56 + 30 \cdot 28$$hsh$, $hsh$7000$hsh$, $hsh$7200$hsh$, $hsh$6500$hsh$, $hsh$7400$hsh$, 'B', 'so', $hsh$7200$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đặt thừa số chung 53: $53 \cdot (64 + 56) = 53 \cdot 120 = 53 \cdot 4 \cdot 30 = 212 \cdot 30$.$hsh$, $hsh$Ta có: $53 \cdot (64 + 56) + 30 \cdot 28 = 53 \cdot 120 + 30 \cdot 28 = 30 \cdot (53 \cdot 4 + 28) = 30 \cdot (212 + 28) = 30 \cdot 240 = 7200$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl1c$hsh$, $hsh$stage_1$hsh$, 'kho', 'dien', $hsh$Thực hiện phép tính: $15 \cdot \left\{44 : \left[6^2 - (5^2 \cdot 7 - 3^4 + 2) : 3\right]\right\} + 115$$hsh$, $hsh$280$hsh$, $hsh$175$hsh$, $hsh$200$hsh$, $hsh$155$hsh$, 'A', 'so', $hsh$280$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tính lũy thừa trước: $6^2 = 36$, $5^2 \cdot 7 = 175$, $3^4 = 81$.$hsh$, $hsh$Trong ngoặc tròn: $5^2 \cdot 7 - 3^4 + 2 = 175 - 81 + 2 = 96$.
Ngoặc vuông: $6^2 - 96 : 3 = 36 - 32 = 4$.
Ngoặc nhọn: $44 : 4 = 11$.
Kết quả: $15 \cdot 11 + 115 = 165 + 115 = 280$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl1c$hsh$, $hsh$stage_1$hsh$, 'kho', 'dien', $hsh$Tính tổng dãy số cách đều: $S = 1 + 3 + 5 + \dots + 99$$hsh$, $hsh$2500$hsh$, $hsh$2450$hsh$, $hsh$2550$hsh$, $hsh$5000$hsh$, 'A', 'so', $hsh$2500$hsh$, $hsh$$S =$$hsh$, $hsh$$hsh$, $hsh$Số số hạng: $(99 - 1) : 2 + 1 = 50$. Tổng bằng: $(99 + 1) \cdot 50 : 2$.$hsh$, $hsh$Số số hạng là 50. Tổng $S = (1 + 99) \cdot 50 : 2 = 100 \cdot 25 = 2500$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl1c$hsh$, $hsh$stage_1$hsh$, 'kho', 'dien', $hsh$Tính tổng dãy số đan dấu: $96 - 92 + \dots + 26 - 22 + 16 - 12 + 6 - 2$$hsh$, $hsh$40$hsh$, $hsh$48$hsh$, $hsh$50$hsh$, $hsh$100$hsh$, 'A', 'so', $hsh$40$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Ghép các cặp số liên tiếp lại: $(96 - 92) + \dots + (16 - 12) + (6 - 2)$. Chú ý quy luật khoảng cách giữa các cặp.$hsh$, $hsh$Nhóm thành các cặp: $(96 - 92) + (86 - 82) + \dots + (16 - 12) + (6 - 2)$.
Mỗi cặp đều có hiệu bằng $4$. Các số bị trừ trong mỗi cặp là $2, 12, 22, \dots, 92$.
Số cặp là: $(92 - 2) : 10 + 1 = 10$ cặp.
Vậy tổng bằng $10 \cdot 4 = 40$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl1d$hsh$, $hsh$stage_1$hsh$, 'kho', 'dien', $hsh$Tính giá trị lũy thừa: $(8^{12} + 8^{13} + 8^{14}) : (8^{10} + 8^{11} + 8^{12})$$hsh$, $hsh$8$hsh$, $hsh$16$hsh$, $hsh$64$hsh$, $hsh$512$hsh$, 'C', 'so', $hsh$64$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Đặt thừa số chung $8^2$ ở số bị chia ra ngoài.$hsh$, $hsh$Ta có: $8^{12} + 8^{13} + 8^{14} = 8^2 \cdot (8^{10} + 8^{11} + 8^{12})$.
Khi chia cho $(8^{10} + 8^{11} + 8^{12})$, ta được kết quả là $8^2 = 64$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl2a$hsh$, $hsh$stage_2$hsh$, 'de', 'trac_nghiem', $hsh$Tìm số tự nhiên $x$ thỏa mãn: $17 - 7x = 3$$hsh$, $hsh$$x = 2$$hsh$, $hsh$$x = 1$$hsh$, $hsh$$x = 3$$hsh$, $hsh$Không có x$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tìm số trừ $7x = 17 - 3 = 14$.$hsh$, $hsh$Ta có: $7x = 17 - 3 = 14 \implies x = 14 : 7 = 2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl2a$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $100 - 7(x - 5) = 58$$hsh$, $hsh$$x = 11$$hsh$, $hsh$$x = 6$$hsh$, $hsh$$x = 12$$hsh$, $hsh$$x = 8$$hsh$, 'A', 'so', $hsh$11$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Tìm $7(x - 5) = 100 - 58 = 42$.$hsh$, $hsh$Ta có: $7(x - 5) = 42 \implies x - 5 = 6 \implies x = 11$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl2b$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $4 \cdot 2^x - 3 = 125$$hsh$, $hsh$$x = 4$$hsh$, $hsh$$x = 5$$hsh$, $hsh$$x = 6$$hsh$, $hsh$$x = 3$$hsh$, 'B', 'so', $hsh$5$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Chuyển vế: $4 \cdot 2^x = 128 = 2^7$.$hsh$, $hsh$$4 \cdot 2^x = 128 \implies 2^x = 128 : 4 = 32 = 2^5 \implies x = 5$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tl2a$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm $x$ biết: $130 - 3(100 - x) = 25$$hsh$, $hsh$$x = 65$$hsh$, $hsh$$x = 35$$hsh$, $hsh$$x = 75$$hsh$, $hsh$$x = 45$$hsh$, 'A', 'so', $hsh$65$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$$3(100 - x) = 130 - 25 = 105 \implies 100 - x = 35$.$hsh$, $hsh$Ta có: $100 - x = 105 : 3 = 35 \implies x = 100 - 35 = 65$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tl2c$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ thỏa mãn: $(x - 5)(2x - 8) = 0$$hsh$, $hsh$$x \in \{5; 4\}$$hsh$, $hsh$$x \in \{5; 8\}$$hsh$, $hsh$$x = 5$$hsh$, $hsh$$x = 4$$hsh$, 'A', 'tap_hop', $hsh$4;5$hsh$, $hsh$$x \in \{$$hsh$, $hsh$$\}$$hsh$, $hsh$Giải từng trường hợp: $x - 5 = 0$ hoặc $2x - 8 = 0$.$hsh$, $hsh$$x - 5 = 0 \implies x = 5$; $2x - 8 = 0 \implies 2x = 8 \implies x = 4$. Vậy $x \in \{5; 4\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tl2a$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $2^4 - 2(15 - x) = 10$$hsh$, $hsh$$x = 12$$hsh$, $hsh$$x = 10$$hsh$, $hsh$$x = 8$$hsh$, $hsh$$x = 14$$hsh$, 'A', 'so', $hsh$12$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$$2^4 = 16$. Chuyển vế: $2(15 - x) = 16 - 10 = 6$.$hsh$, $hsh$$15 - x = 3 \implies x = 15 - 3 = 12$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tl2b$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $12 \cdot (3^x + 3) = 12^2$$hsh$, $hsh$$x = 1$$hsh$, $hsh$$x = 2$$hsh$, $hsh$$x = 3$$hsh$, $hsh$$x = 0$$hsh$, 'B', 'so', $hsh$2$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Chia cả hai vế cho $12$ trước.$hsh$, $hsh$Chia hai vế cho $12$: $3^x + 3 = 12 \implies 3^x = 9 = 3^2 \implies x = 2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl2a$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $90 - [4^2 + (x - 6)] = 20$$hsh$, $hsh$x = 50$hsh$, $hsh$x = 60$hsh$, $hsh$x = 54$hsh$, $hsh$x = 44$hsh$, 'B', 'so', $hsh$60$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Tìm cụm trong ngoặc vuông trước: $[4^2 + (x - 6)] = 90 - 20 = 70$.$hsh$, $hsh$Ta có: $16 + (x - 6) = 70 \implies x - 6 = 70 - 16 = 54 \implies x = 54 + 6 = 60$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl2b$hsh$, $hsh$stage_2$hsh$, 'trung_binh', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $31 - (x + 8) = 3 \cdot (2^5 - 5^2)$$hsh$, $hsh$x = 2$hsh$, $hsh$x = 3$hsh$, $hsh$x = 5$hsh$, $hsh$x = 8$hsh$, 'A', 'so', $hsh$2$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Tính giá trị vế phải trước: $2^5 = 32$ và $5^2 = 25$.$hsh$, $hsh$Vế phải: $3 \cdot (32 - 25) = 3 \cdot 7 = 21$.
Phương trình trở thành: $31 - (x + 8) = 21 \implies x + 8 = 31 - 21 = 10 \implies x = 2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl2b$hsh$, $hsh$stage_2$hsh$, 'kho', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $(5x - 20)(2x^3 - 54) = 0$$hsh$, $hsh$$x \in \{4; 3\}$$hsh$, $hsh$$x \in \{4; 9\}$$hsh$, $hsh$$x \in \{2; 3\}$$hsh$, $hsh$$x = 4$$hsh$, 'A', 'tap_hop', $hsh$3;4$hsh$, $hsh$$x \in \{$$hsh$, $hsh$$\}$$hsh$, $hsh$Phương trình tích: $5x - 20 = 0$ hoặc $2x^3 - 54 = 0$.$hsh$, $hsh$- $5x - 20 = 0 \implies 5x = 20 \implies x = 4$.
- $2x^3 - 54 = 0 \implies 2x^3 = 54 \implies x^3 = 27 = 3^3 \implies x = 3$.
Vậy $x \in \{4; 3\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl2c$hsh$, $hsh$stage_2$hsh$, 'kho', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $3^x + 3^{x+2} = 90$$hsh$, $hsh$$x = 1$$hsh$, $hsh$$x = 2$$hsh$, $hsh$$x = 3$$hsh$, $hsh$$x = 4$$hsh$, 'B', 'so', $hsh$2$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Đặt $3^x$ làm thừa số chung: $3^x(1 + 3^2) = 90$.$hsh$, $hsh$Ta có: $3^x \cdot (1 + 9) = 90 \implies 3^x \cdot 10 = 90 \implies 3^x = 9 = 3^2 \implies x = 2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl2c$hsh$, $hsh$stage_2$hsh$, 'kho', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $1000 : [30 + (2^x - 6)] = 3^2 + 4^2$$hsh$, $hsh$x = 3$hsh$, $hsh$x = 4$hsh$, $hsh$x = 5$hsh$, $hsh$x = 6$hsh$, 'B', 'so', $hsh$4$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$Tính $3^2 + 4^2 = 9 + 16 = 25$. Sau đó tìm giá trị trong ngoặc vuông.$hsh$, $hsh$$[30 + (2^x - 6)] = 1000 : 25 = 40$.
$2^x - 6 = 40 - 30 = 10 \implies 2^x = 16 = 2^4 \implies x = 4$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl2d$hsh$, $hsh$stage_2$hsh$, 'kho', 'dien', $hsh$Tìm số tự nhiên $x$ biết: $(x + 2) \in \text{Ư}(2x + 10)$$hsh$, $hsh$$x \in \{0; 1; 4\}$$hsh$, $hsh$$x \in \{1; 4; 6\}$$hsh$, $hsh$$x \in \{0; 1; 2; 4\}$$hsh$, $hsh$$x \in \{2; 4; 6\}$$hsh$, 'A', 'tap_hop', $hsh$0;1;4$hsh$, $hsh$$x \in \{$$hsh$, $hsh$$\}$$hsh$, $hsh$Tách $2x + 10 = 2(x + 2) + 6$. Khi đó $(x + 2)$ phải là ước của 6.$hsh$, $hsh$Ta có: $2x + 10 = 2(x + 2) + 6$.
Để $(2x + 10) \ \vdots \ (x + 2)$ thì $6 \ \vdots \ (x + 2)$.
Vì $x \in \mathbb{N}$ nên $x + 2 \ge 2$. Do đó $x + 2 \in \{2; 3; 6\}$.
- $x + 2 = 2 \implies x = 0$.
- $x + 2 = 3 \implies x = 1$.
- $x + 2 = 6 \implies x = 4$.
Vậy $x \in \{0; 1; 4\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tn1$hsh$, $hsh$stage_3$hsh$, 'de', 'trac_nghiem', $hsh$Các số nguyên tố nhỏ hơn 10 là:$hsh$, $hsh$2; 3; 5; 7; 9$hsh$, $hsh$2; 3; 5; 7$hsh$, $hsh$1; 3; 5; 7$hsh$, $hsh$2; 3; 5$hsh$, 'B', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Lưu ý 1 không phải là số nguyên tố và 9 là hợp số.$hsh$, $hsh$Các số nguyên tố nhỏ hơn 10 gồm có: 2; 3; 5; 7.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tn2$hsh$, $hsh$stage_3$hsh$, 'de', 'trac_nghiem', $hsh$Tính $\text{ƯCLN}(9; 63)$:$hsh$, $hsh$63$hsh$, $hsh$1$hsh$, $hsh$3$hsh$, $hsh$9$hsh$, 'D', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Vì 63 chia hết cho 9 nên ƯCLN của hai số chính là số nhỏ hơn.$hsh$, $hsh$Do $63 \ \vdots \ 9$ nên $\text{ƯCLN}(9; 63) = 9$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tn2$hsh$, $hsh$stage_3$hsh$, 'de', 'trac_nghiem', $hsh$Tập hợp X các số tự nhiên nhỏ hơn 6 và là ước của 8 là:$hsh$, $hsh$$X = \{0; 1; 2\}$$hsh$, $hsh$$X = \{0; 1; 2; 4\}$$hsh$, $hsh$$X = \{1; 2; 4\}$$hsh$, $hsh$$X = \{2; 4\}$$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Ước tự nhiên của 8 là 1, 2, 4, 8. Chọn các số nhỏ hơn 6 (lưu ý 0 không phải là ước).$hsh$, $hsh$Các ước của 8 nhỏ hơn 6 là 1, 2, 4. Vậy $X = \{1; 2; 4\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tn4$hsh$, $hsh$stage_3$hsh$, 'de', 'trac_nghiem', $hsh$Nếu $x$ là số nguyên tố lớn nhất có hai chữ số và $y$ là số nguyên tố nhỏ nhất thì giá trị của $x + y$ là:$hsh$, $hsh$95$hsh$, $hsh$97$hsh$, $hsh$99$hsh$, $hsh$101$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Số nguyên tố lớn nhất có hai chữ số là $97$, số nguyên tố nhỏ nhất là $2$.$hsh$, $hsh$Số nguyên tố lớn nhất có hai chữ số là $x = 97$. Số nguyên tố nhỏ nhất là $y = 2$. Do đó $x + y = 97 + 2 = 99$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl3$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Một thùng cam có số lượng trong khoảng từ 200 đến 600 quả. Nếu xếp vào mỗi hộp 6 quả, 10 quả, 12 quả hay 14 quả đều vừa đủ. Hỏi có bao nhiêu quả cam?$hsh$, $hsh$420 quả$hsh$, $hsh$210 quả$hsh$, $hsh$840 quả$hsh$, $hsh$360 quả$hsh$, 'A', 'so', $hsh$420$hsh$, $hsh$$hsh$, $hsh$quả$hsh$, $hsh$Số quả cam là bội chung của 6, 10, 12, 14 và nằm trong khoảng từ 200 đến 600.$hsh$, $hsh$BCNN(6, 10, 12, 14) = 420. Vì $200 < 420 < 600$ nên số quả cam trong thùng là 420 quả.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl3$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Một đội y tế có 24 bác sĩ và 108 y tá. Có thể chia đội đó thành nhiều nhất mấy tổ để số bác sĩ và y tá chia đều?$hsh$, $hsh$6 tổ$hsh$, $hsh$12 tổ$hsh$, $hsh$24 tổ$hsh$, $hsh$18 tổ$hsh$, 'B', 'so', $hsh$12$hsh$, $hsh$$hsh$, $hsh$tổ$hsh$, $hsh$Số tổ nhiều nhất là $\text{ƯCLN}(24, 108)$.$hsh$, $hsh$Ta có: $24 = 2^3 \cdot 3$; $108 = 2^2 \cdot 3^3$. $\text{ƯCLN}(24, 108) = 2^2 \cdot 3 = 12$. Vậy có thể chia nhiều nhất thành 12 tổ.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tn2$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Trong các phân số $\frac{50}{94}$; $\frac{13}{56}$; $\frac{12}{60}$; $\frac{7}{14}$, phân số nào là phân số tối giản? (nhập dạng a/b)$hsh$, $hsh$$\frac{50}{94}$$hsh$, $hsh$$\frac{13}{56}$$hsh$, $hsh$$\frac{12}{60}$$hsh$, $hsh$$\frac{7}{14}$$hsh$, 'B', 'phan_so', $hsh$13/56$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Phân số tối giản có tử số và mẫu số nguyên tố cùng nhau (ƯCLN = 1).$hsh$, $hsh$Số 13 là số nguyên tố và 56 không chia hết cho 13, nên $\text{ƯCLN}(13, 56) = 1$. Phân số $\frac{13}{56}$ tối giản.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tl3$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Số học sinh khối 6 trong khoảng từ 300 đến 400 em. Biết xếp hàng 30 hay 45 đều vừa đủ. Tính số học sinh.$hsh$, $hsh$360 học sinh$hsh$, $hsh$390 học sinh$hsh$, $hsh$330 học sinh$hsh$, $hsh$350 học sinh$hsh$, 'A', 'so', $hsh$360$hsh$, $hsh$$hsh$, $hsh$học sinh$hsh$, $hsh$Số học sinh là bội chung của 30 và 45 nằm giữa 300 và 400.$hsh$, $hsh$$\text{BCNN}(30, 45) = 90$. Các bội là: 90, 180, 270, 360, 450. Số nằm trong khoảng từ 300 đến 400 là 360.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tl2a$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Tìm $x$ biết $x \ \vdots \ 10$, $x \ \vdots \ 15$ và $30 < x < 90$:$hsh$, $hsh$$x = 60$$hsh$, $hsh$$x = 45$$hsh$, $hsh$$x = 75$$hsh$, $hsh$$x = 80$$hsh$, 'A', 'so', $hsh$60$hsh$, $hsh$$x =$$hsh$, $hsh$$hsh$, $hsh$$x$ là bội chung của 10 và 15, BCNN(10, 15) = 30.$hsh$, $hsh$Bội chung của 10 và 15 là $30, 60, 90, \dots$ Số thỏa mãn $30 < x < 90$ là 60.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tl3$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Hai bạn cùng đi xe buýt về nhà. Xe của An Bình cứ 12 phút có 1 chuyến, xe của Hoàng Quân cứ 18 phút có 1 chuyến. Hai bạn phải cùng chờ ít nhất bao nhiêu phút để cả hai xe cùng đến?$hsh$, $hsh$36 phút$hsh$, $hsh$72 phút$hsh$, $hsh$54 phút$hsh$, $hsh$24 phút$hsh$, 'A', 'so', $hsh$36$hsh$, $hsh$$hsh$, $hsh$phút$hsh$, $hsh$Thời gian chờ ít nhất là BCNN của 12 và 18.$hsh$, $hsh$$\text{BCNN}(12, 18) = 36$. Vậy sau ít nhất 36 phút cả 2 xe lại cùng đến bến.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tn2$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Cho số $N = 2016 - 20 \cdot 16$. Trong các số $2$; $3$; $5$; $9$, số $N$ chia hết cho số nào?$hsh$, $hsh$$N \ \vdots \ 2$$hsh$, $hsh$$N \ \vdots \ 3$$hsh$, $hsh$$N \ \vdots \ 5$$hsh$, $hsh$$N \ \vdots \ 9$$hsh$, 'A', 'so', $hsh$2$hsh$, $hsh$$N \ \vdots$$hsh$, $hsh$$hsh$, $hsh$Tính giá trị của $N$ hoặc xét chữ số tận cùng của $2016$ và tích $20 \cdot 16$.$hsh$, $hsh$Ta có: $20 \cdot 16 = 320$, nên $N = 2016 - 320 = 1696$.
- $1696$ có chữ số tận cùng là $6$ nên $N \ \vdots \ 2$.
- Tổng các chữ số $1+6+9+6 = 22$ không chia hết cho $3$ và $9$.
- Chữ số tận cùng khác $0$ và $5$ nên $N$ không chia hết cho $5$.
Vậy khẳng định đúng là $N \ \vdots \ 2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tn3$hsh$, $hsh$stage_3$hsh$, 'trung_binh', 'dien', $hsh$Cho $m = 2^1 \cdot 3$, $n = 3 \cdot 5^2$, $p = 2 \cdot 5 \cdot 7$. Vậy $\text{ƯCLN}(m, n, p)$ là:$hsh$, $hsh$2$hsh$, $hsh$15$hsh$, $hsh$1$hsh$, $hsh$10$hsh$, 'C', 'so', $hsh$1$hsh$, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tìm các thừa số nguyên tố chung của cả ba số $m, n, p$.$hsh$, $hsh$Xét các thừa số nguyên tố: $m$ có thừa số $2, 3$; $n$ có thừa số $3, 5$; $p$ có thừa số $2, 5, 7$. Không có thừa số nguyên tố nào xuất hiện đồng thời ở cả ba số, do đó $\text{ƯCLN}(m, n, p) = 1$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tl3$hsh$, $hsh$stage_3$hsh$, 'kho', 'dien', $hsh$Học sinh xếp hàng 2, hàng 3, hàng 5, hàng 7 đều dư 1 em. Biết số học sinh trong khoảng từ 400 đến 500 em. Số học sinh là:$hsh$, $hsh$421 em$hsh$, $hsh$420 em$hsh$, $hsh$441 em$hsh$, $hsh$481 em$hsh$, 'A', 'so', $hsh$421$hsh$, $hsh$$hsh$, $hsh$em$hsh$, $hsh$Số học sinh trừ 1 chia hết cho 2, 3, 5, 7. $\text{BCNN}(2, 3, 5, 7) = 210$.$hsh$, $hsh$Bội chung trong khoảng 400 - 500 là 420. Vậy số học sinh là $420 + 1 = 421$ em.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl3$hsh$, $hsh$stage_3$hsh$, 'kho', 'dien', $hsh$Số học sinh khối 6 khi xếp hàng 12, 15, 18 đều thừa 4 học sinh, nhưng xếp hàng 26 thì vừa đủ. Biết số học sinh nhỏ hơn 400. Số học sinh khối 6 là:$hsh$, $hsh$184 học sinh$hsh$, $hsh$364 học sinh$hsh$, $hsh$360 học sinh$hsh$, $hsh$390 học sinh$hsh$, 'B', 'so', $hsh$364$hsh$, $hsh$$hsh$, $hsh$học sinh$hsh$, $hsh$Gọi số học sinh là $a$. Khi đó $a - 4$ chia hết cho 12, 15, 18 và $a \ \vdots \ 26$.$hsh$, $hsh$Ta có: $(a - 4) \in \text{BC}(12, 15, 18)$.
$\text{BCNN}(12, 15, 18) = 180$. Vì $a < 400$ nên $a - 4 \in \{180; 360\} \implies a \in \{184; 364\}$.
Kiểm tra điều kiện xếp hàng 26 vừa đủ ($a \ \vdots \ 26$):
- $184 : 26 = 7$ dư 2 (loại).
- $364 : 26 = 14$ (thỏa mãn).
Vậy số học sinh là 364.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tn4$hsh$, $hsh$stage_4$hsh$, 'de', 'trac_nghiem', $hsh$Khẳng định nào sau đây SAI đối với hình lục giác đều?$hsh$, $hsh$Các góc bằng nhau bằng $60^\circ$$hsh$, $hsh$Ba đường chéo chính bằng nhau$hsh$, $hsh$Các cạnh bằng nhau$hsh$, $hsh$Hình lục giác đều tạo bởi 6 tam giác đều bằng nhau$hsh$, 'A', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Trong hình lục giác đều, mỗi góc có số đo bằng $120^\circ$, không phải $60^\circ$.$hsh$, $hsh$Mỗi góc của hình lục giác đều bằng $120^\circ$, nên khẳng định A (các góc bằng $60^\circ$) là sai. Các khẳng định còn lại đều đúng: sáu cạnh bằng nhau, ba đường chéo chính bằng nhau, và hình được ghép từ 6 tam giác đều.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tn3$hsh$, $hsh$stage_4$hsh$, 'de', 'trac_nghiem', $hsh$Khẳng định nào sau đây là ĐÚNG trong hình chữ nhật?$hsh$, $hsh$Bốn góc bằng nhau và bằng $60^\circ$$hsh$, $hsh$Hai đường chéo không bằng nhau$hsh$, $hsh$Bốn góc bằng nhau và bằng $90^\circ$$hsh$, $hsh$Hai đường chéo song song với nhau$hsh$, 'C', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Hình chữ nhật có 4 góc vuông và hai đường chéo bằng nhau.$hsh$, $hsh$Trong hình chữ nhật, bốn góc đều là góc vuông ($90^\circ$).$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tn4$hsh$, $hsh$stage_4$hsh$, 'de', 'trac_nghiem', $hsh$Mỗi góc của hình tam giác đều bằng bao nhiêu độ?$hsh$, $hsh$$45^\circ$$hsh$, $hsh$$60^\circ$$hsh$, $hsh$$90^\circ$$hsh$, $hsh$$120^\circ$$hsh$, 'B', null, null, $hsh$$hsh$, $hsh$$hsh$, $hsh$Tam giác đều có 3 cạnh bằng nhau và 3 góc bằng nhau.$hsh$, $hsh$Trong tam giác đều, mỗi góc có số đo bằng $60^\circ$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tn4$hsh$, $hsh$stage_4$hsh$, 'trung_binh', 'dien', $hsh$Hình thoi ABCD có diện tích $20\text{ cm}^2$ và đường chéo AC bằng 10cm. Đường chéo BD có độ dài là:$hsh$, $hsh$2 cm$hsh$, $hsh$3 cm$hsh$, $hsh$4 cm$hsh$, $hsh$5 cm$hsh$, 'C', 'so', $hsh$4$hsh$, $hsh$$BD =$$hsh$, $hsh$cm$hsh$, $hsh$Diện tích hình thoi: $S = \frac{1}{2} d_1 \cdot d_2 \implies d_2 = 2S : d_1$.$hsh$, $hsh$Độ dài đường chéo BD là: $2 \cdot 20 : 10 = 4\text{ cm}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl4$hsh$, $hsh$stage_4$hsh$, 'trung_binh', 'dien', $hsh$Cho hình chữ nhật MNPQ có diện tích $50\text{ cm}^2$ và chiều dài gấp đôi chiều rộng. Hình thoi ABCD có hai đường chéo AC và BD lần lượt bằng chiều rộng và chiều dài của MNPQ. Tính diện tích hình thoi ABCD.$hsh$, $hsh$50 cm²$hsh$, $hsh$25 cm²$hsh$, $hsh$100 cm²$hsh$, $hsh$12,5 cm²$hsh$, 'B', 'so', $hsh$25$hsh$, $hsh$$hsh$, $hsh$$\text{cm}^2$$hsh$, $hsh$Công thức diện tích hình thoi là $S = \frac{1}{2} d_1 \cdot d_2$.$hsh$, $hsh$Gọi độ dài hai đường chéo của hình thoi là $d_1, d_2$. Theo đề bài, $d_1, d_2$ lần lượt là chiều rộng và chiều dài của hình chữ nhật $MNPQ$.
Diện tích hình chữ nhật là $S_{MNPQ} = d_1 \cdot d_2 = 50\text{ cm}^2$.
Diện tích hình thoi là $S_{ABCD} = \frac{1}{2} \cdot d_1 \cdot d_2 = \frac{1}{2} \cdot 50 = 25\text{ cm}^2$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de05_tl4b$hsh$, $hsh$stage_4$hsh$, 'kho', 'dien', $hsh$Thửa ruộng hình thang có 2 đáy là 15m và 20m, chiều cao 5m. Năng suất đạt 0,6 kg/m². Sản lượng thóc thu được là:$hsh$, $hsh$52,5 kg$hsh$, $hsh$87,5 kg$hsh$, $hsh$105 kg$hsh$, $hsh$75 kg$hsh$, 'A', 'so', $hsh$52,5$hsh$, $hsh$$hsh$, $hsh$kg$hsh$, $hsh$Diện tích hình thang: $S = (a + b) \cdot h : 2$. Sản lượng = $S \times 0,6$.$hsh$, $hsh$Diện tích: $(15 + 20) \cdot 5 : 2 = 35 \cdot 5 : 2 = 87,5\text{ m}^2$. Sản lượng: $87,5 \times 0,6 = 52,5\text{ kg}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de03_tl5$hsh$, $hsh$stage_5$hsh$, 'kho', 'dien', $hsh$So sánh hai lũy thừa $A = 333^{444}$ và $B = 444^{333}$. Điền dấu thích hợp ($>$, $<$ hoặc $=$):$hsh$, $hsh$$A > B$$hsh$, $hsh$$A < B$$hsh$, $hsh$$A = B$$hsh$, $hsh$Không so sánh được$hsh$, 'A', 'dau', $hsh$>$hsh$, $hsh$$A$$hsh$, $hsh$$B$$hsh$, $hsh$Đưa về cùng số mũ 111: $A = (333^4)^{111}$ và $B = (444^3)^{111}$.$hsh$, $hsh$Ta có: $333^4 = (3 \cdot 111)^4 = 81 \cdot 111^4$. $444^3 = (4 \cdot 111)^3 = 64 \cdot 111^3$. Rõ ràng $81 \cdot 111^4 > 64 \cdot 111^3$, nên $333^{444} > 444^{333}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de04_tl5$hsh$, $hsh$stage_5$hsh$, 'kho', 'dien', $hsh$Cho $M = 2 + 2^2 + 2^3 + \dots + 2^{20}$. Trong các số $7$; $9$; $15$; $17$, số $M$ chia hết cho số nào?$hsh$, $hsh$15$hsh$, $hsh$7$hsh$, $hsh$9$hsh$, $hsh$17$hsh$, 'A', 'so', $hsh$15$hsh$, $hsh$$M \ \vdots$$hsh$, $hsh$$hsh$, $hsh$Ghép nhóm 4 số hạng liên tiếp: $2 + 2^2 + 2^3 + 2^4 = 30 = 15 \cdot 2$.$hsh$, $hsh$Mỗi nhóm 4 số hạng: $2^k(2 + 2^2 + 2^3 + 2^4) = 2^k \cdot 30 = 2^k \cdot 15 \cdot 2 \ \vdots \ 15$. Dãy có 20 số hạng chia đều thành 5 nhóm, nên $M \ \vdots \ 15$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de06_tl5$hsh$, $hsh$stage_5$hsh$, 'kho', 'dien', $hsh$Tìm số tự nhiên $x$ sao cho $(4x + 7) \ \vdots \ (2x + 1)$:$hsh$, $hsh$$x = 2$$hsh$, $hsh$$x = 1$$hsh$, $hsh$$x \in \{0; 2\}$$hsh$, $hsh$$x = 0$$hsh$, 'C', 'tap_hop', $hsh$0;2$hsh$, $hsh$$x \in \{$$hsh$, $hsh$$\}$$hsh$, $hsh$Tách $4x + 7 = 2(2x + 1) + 5$. Khi đó $5 \ \vdots \ (2x + 1)$.$hsh$, $hsh$Ta có: $4x + 7 = 2(2x + 1) + 5$.
Để $(4x + 7) \ \vdots \ (2x + 1)$ thì $5 \ \vdots \ (2x + 1)$, nên $2x + 1 \in \{1; 5\}$.
- $2x + 1 = 1 \implies x = 0$.
- $2x + 1 = 5 \implies x = 2$.
Vậy $x \in \{0; 2\}$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de07_tl5$hsh$, $hsh$stage_5$hsh$, 'kho', 'dien', $hsh$Cho tổng $A = 3 + 3^2 + 3^3 + \dots + 3^{2021}$. Tìm số dư khi chia $A$ cho 13:$hsh$, $hsh$Dư 3$hsh$, $hsh$Dư 0$hsh$, $hsh$Dư 12$hsh$, $hsh$Dư 1$hsh$, 'C', 'so', $hsh$12$hsh$, $hsh$Số dư:$hsh$, $hsh$$hsh$, $hsh$Để ý $3 + 3^2 + 3^3 = 39$ chia hết cho $13$. Hãy nhóm ba số hạng liên tiếp.$hsh$, $hsh$Nhóm ba số hạng liên tiếp: $3^k + 3^{k+1} + 3^{k+2} = 3^k \cdot 13 \ \vdots \ 13$.
Vì $2021 = 3 \cdot 673 + 2$, ta tách hai số hạng đầu ra:
$A = (3 + 3^2) + (3^3 + 3^4 + 3^5) + \dots + (3^{2019} + 3^{2020} + 3^{2021})$.
Các nhóm trong ngoặc sau đều chia hết cho $13$, còn $3 + 3^2 = 12$.
Vậy $A$ chia cho $13$ dư $12$.$hsh$) on conflict (id) do nothing;
insert into public.questions (id, stage_id, muc_do, loai, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung, kieu_dien, dap_an_dien, tien_to, don_vi, goi_y, loi_giai) values ($hsh$de09_tl5$hsh$, $hsh$stage_5$hsh$, 'kho', 'dien', $hsh$Cho $A = 3^1 + 3^2 + 3^3 + \dots + 3^{102}$. Tìm số dư khi chia $A$ cho $40$.$hsh$, $hsh$12$hsh$, $hsh$0$hsh$, $hsh$3$hsh$, $hsh$39$hsh$, 'A', 'so', $hsh$12$hsh$, $hsh$Số dư:$hsh$, $hsh$$hsh$, $hsh$Để ý $3^3 + 3^4 + 3^5 + 3^6 = 3^3 \cdot (1 + 3 + 9 + 27) = 3^3 \cdot 40$. Hãy nhóm bốn số hạng liên tiếp.$hsh$, $hsh$Dãy có $102$ số hạng. Tách hai số hạng đầu, $100$ số hạng còn lại chia thành $25$ nhóm bốn số liên tiếp:
$A = (3 + 3^2) + (3^3 + 3^4 + 3^5 + 3^6) + \dots + (3^{99} + 3^{100} + 3^{101} + 3^{102})$.
Mỗi nhóm bằng $3^k \cdot (1 + 3 + 9 + 27) = 3^k \cdot 40$ nên chia hết cho $40$.
Vậy $A$ chia cho $40$ dư $3 + 3^2 = 12$.$hsh$) on conflict (id) do nothing;
